config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  root to: 'home#top'

  get 'home/sample', to: 'home#sample'
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  resources :users, only: %i[new create update destroy]
  resources :advice_materials, only: %i[new create edit update]
  resources :hairs_features, only: %i[new create edit update]
  resource :user_information, only: %i[show edit update]
  resources :weather_forecasts, only: %i[new create update show]
  resources :password_resets, only: %i[new create edit update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_before_login_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navigation navbar-light bg-light">

    <%= link_to root_path, class: 'navbar-brand' do %>
      <%= image_tag 'logo.png' %>
    <% end %>

    <button class='navbar-toggler' data-toggle='collapse' data-target='#navbarSupportedContent' aria-controls='navbarSupportedContent' aria-expanded='false' aria-label='Toggle navigation'>
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto main-nav align-items-center">
        <li class="nav-item">
          <%= link_to (t 'defaults.login'), login_path ,class: 'nav-link' %>
        </li>
      </ul>
    </div>
  </nav>
</header>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
    <div id="error_messages" class="alert alert-danger">
        <ul class="mb-0">
            <% object.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
<% end %>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/shared/_footer.html.erb
<footer id='footer' class="footer-bottom">
  <div class="container">
    <div class="row">
      <div class="col-sm-6 col-12">
        <div class="copyright">
          <p>Copyright © 2023. YURI SEMBA</p>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<header>
<nav class="navbar navbar-expand-lg navigation navbar-light bg-light">

  <%= link_to root_path, class: 'navbar-brand' do %>
    <%= image_tag 'logo.png' %>
  <% end %>
  <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto main-nav align-items-center">
      <li class="nav-item dropdown dropdown-slide">
        <li class="nav-item">
          <%= link_to (t 'defaults.user_information'), user_information_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to (t 'defaults.hair_advice'), new_weather_forecast_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to (t 'defaults.logout'), logout_path, class: 'nav-link', method: :delete %>
        </li>
       <div class="dropdown-menu dropdown-menu-right">
          <div class="dropdown-item"><%= current_user.decorate.full_name %></div>
          <div class="dropdown-divider"></div>
          <%= link_to (t 'defaults.user_information'), user_information_path, class: 'dropdown-item' %>
          <%= link_to (t 'defaults.hair_advice'), new_weather_forecast_path, class: 'dropdown-item' %>
          <%= link_to (t 'defaults.logout'), logout_path, class: 'dropdown-item', method: :delete %>
        </div>
      </li>
    </ul>
  </div>
</nav>
</header>