config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  root to: 'home#top'

  get 'home/sample', to: 'home#sample'
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  resources :users, only: %i[new create update destroy]
  resources :advice_materials, only: %i[new create edit update]
  resources :hairs_features, only: %i[new create edit update]
  resource :user_information, only: %i[show edit update]
  resources :weather_forecasts, only: %i[new create update show]
  resources :password_resets, only: %i[new create edit update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :require_login
  def top
    if logged_in? && current_user.advice_material.present? && current_user.hairs_feature.present?
      redirect_to new_weather_forecast_path
    elsif logged_in? && current_user.advice_material.nil?
      redirect_to new_advice_material_path
    elsif logged_in? && current_user.hairs_feature.nil?
      redirect_to new_hairs_feature_path
    end
  end

  def sample; end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/sample.html.erb
<div class='top-wrapper'>
  <div class='top-inner-text'>
    <h2>今日の那覇の天気は</h2>
      <%= image_tag "http://openweathermap.org/img/wn/10d@2x.png" %>
    <h2>今日の気温は</h2>
    <h4>最高21度、最低19度です。</h4>
      <h2>湿度は</h2>
      <h4>"77％です。</h4>
      <h2>剛毛癖っ毛さんの髪型注意報</h2>
      <h4>湿度高いです。前日夜からしっかりケアを。</br>スタイルング時は、クリーム系やオイル系のトリートメント材の使用をお勧め。</h4>
    <div class="check">
      <%= link_to (t '.to_top'), root_path , class: 'btn btn-primary' %>
    </div>
  </div>
</div>

app/views/home/top.html.erb
<div class='top-wrapper'>
  <div class='top-inner-text'>
    <h1>WEATHER FORECAST </br>with</br>HAIR STYLE ADVICE</h1>
    <h5>癖っ毛さん専用のお天気予報です。</br>
    天気予報とともに、髪のうねり具合を予想しお手入れ方法を、アドバイスをしてくれます。</h5>
      <div class="check">
        <%= link_to (t '.to_sample'), home_sample_path , class: 'btn btn-primary' %>
      </div>
      <div class="actions">
        <%= link_to (t 'defaults.login'), login_path , class: 'btn btn-primary' %>
        <%= link_to (t 'defaults.register'), new_user_path, class: 'btn btn-primary' %>
      </div>
  </div>
</div>