config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  root to: 'home#top'

  get 'home/sample', to: 'home#sample'
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  resources :users, only: %i[new create update destroy]
  resources :advice_materials, only: %i[new create edit update]
  resources :hairs_features, only: %i[new create edit update]
  resource :user_information, only: %i[show edit update]
  resources :weather_forecasts, only: %i[new create update show]
  resources :password_resets, only: %i[new create edit update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/user_informations_controller.rb
class UserInformationsController < ApplicationController
  before_action :set_user, only: %i[show edit update]
  before_action :set_advice_material, only: %i[show]
  before_action :set_hairs_feature, only: %i[show]
  def show
    @city_id = current_user.advice_material.city_id
    @date = current_user.advice_material.forecast_date
  end

  def edit; end

  def update
    if @user.update(user_params)
      redirect_to user_information_path, success: t('defaults.message.update', item: User.model_name.human)
    else
      flash.now[:danger] = t('defaults.message.update_fail', item: User.model_name.human)
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :last_name, :first_name)
  end

  def set_user
    @user = User.find(current_user.id)
  end

  def set_advice_material
    @advice_material = current_user.advice_material
  end

  def set_hairs_feature
    @hairs_feature = current_user.hairs_feature
  end
end

app/views/user_informations/edit.html.erb
<div class="information-wrapper">
  <div class="information-inner-text">
    <% content_for(:title, t('.title')) %>
    <div class="container">
      <div class="row">
        <div class="col-md-10 offset-md-1">
          <h1><%= t('.title') %></h1>
            <%= form_with model: @user, url: user_information_path, local: true do |f| %>
              <%= render 'shared/error_messages', object: f.object %>
              <%= f.label :email %>
              <%= f.email_field :email, class:"form-control mb-3" %>
              <%= f.label :last_name %>
              <%= f.text_field :last_name, class:"form-control mb-3" %>
              <%= f.label :first_name %>
              <%= f.text_field :first_name, class:"form-control mb-3" %>
            
              <%= f.submit t('defaults.update'), class: "btn btn-primary" %>
            <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/user_informations/show.html.erb
<div class="information-wrapper">
  <div class="information-inner-text">
    <div class="container pt-3">
      <div class="row">
        <div class="col-md-10 offset-md-1">
          <h1 class="float-left mb-5"><%= t('.title') %></h1>
          <%= link_to t('defaults.edit'), edit_user_information_path, class: 'btn btn-primary float-right' %>
            <table class="table text-white">
              <tr>
                <th scope="row"><%= t(User.human_attribute_name(:email)) %></th>
                <td><%= current_user.email %></td>
              </tr>
              <tr>
                <th scope="row"><%= t(User.human_attribute_name(:full_name)) %></th>
                <td><%= current_user.decorate.full_name %></td>
              </tr>
           </table>
        </div>
        <div class="col-md-10 offset-md-1">
          <h1 class="float-left mb-5"><%= t('.my_weather') %></h1>
          <%= link_to t('defaults.edit'), edit_advice_material_path(@advice_material), class: 'btn btn-primary float-right' %>
            <table class="table text-white">
              <tr>
                <th scope="row"><%= t(AdviceMaterial.human_attribute_name(:city)) %></th>
                <td><%= City.where(id: @city_id).pluck(:city_name).join %></td>
              </tr>
              <tr>
                <th scope="row"><%= t(AdviceMaterial.human_attribute_name(:forecast_date)) %></th>
                <td><%= current_user.advice_material.forecast_date %></td>
              </tr>
            </table>
        </div>
        <div class="col-md-10 offset-md-1">
          <h1 class="float-left mb-5"><%= t('.my_hair_feature') %></h1>
          <%= link_to t('defaults.edit'), edit_hairs_feature_path(@hairs_feature), class: 'btn btn-primary float-right' %>
          <table class="table text-white">
            <tr>
              <th scope="row"><%= t(HairsFeature.human_attribute_name(:hair_type)) %></th>
              <td><%= current_user.hairs_feature.hair_type %></td>
            </tr>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>